// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_8b8VrC2N0EmLFy8HuBLoT5BZ1LWKrE0',
    appId: '1:528555148258:web:3f7e771841d1e6a91eafbb',
    messagingSenderId: '528555148258',
    projectId: 'syne-wave',
    authDomain: 'syne-wave.firebaseapp.com',
    storageBucket: 'syne-wave.firebasestorage.app',
    measurementId: 'G-SGHLG4N9ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5HgoxVM90ntOI8VuYBYKWT7BEH1BxNUQ',
    appId: '1:528555148258:android:55f6cfde5968d6ee1eafbb',
    messagingSenderId: '528555148258',
    projectId: 'syne-wave',
    storageBucket: 'syne-wave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKbfFd1GqHyLyNiQk5x8v8zkNMYxNo6A',
    appId: '1:528555148258:ios:5f9b70f0208de60b1eafbb',
    messagingSenderId: '528555148258',
    projectId: 'syne-wave',
    storageBucket: 'syne-wave.firebasestorage.app',
    iosBundleId: 'com.example.chatV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmKbfFd1GqHyLyNiQk5x8v8zkNMYxNo6A',
    appId: '1:528555148258:ios:540e3a27f50671aa1eafbb',
    messagingSenderId: '528555148258',
    projectId: 'syne-wave',
    storageBucket: 'syne-wave.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_8b8VrC2N0EmLFy8HuBLoT5BZ1LWKrE0',
    appId: '1:528555148258:web:261a968018a59d581eafbb',
    messagingSenderId: '528555148258',
    projectId: 'syne-wave',
    authDomain: 'syne-wave.firebaseapp.com',
    storageBucket: 'syne-wave.firebasestorage.app',
    measurementId: 'G-W68WXX9T1M',
  );
}
